# Generated by Django 3.2 on 2021-05-01 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breadcat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sandwich',
            fields=[
                ('id', models.BigAutoField(help_text='Sandwich ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='content',
            name='id',
            field=models.BigAutoField(help_text='Content ID', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='content',
            name='sandwich_id',
            field=models.ForeignKey(db_column='sandwich_id', default='1', on_delete=django.db.models.deletion.CASCADE, related_name='sandwich', to='breadcat.sandwich'),
        ),
    ]
