# Generated by Django 3.2 on 2021-05-01 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breadcat', '0002_auto_20210501_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='sandwich_id',
            field=models.ForeignKey(db_column='sandwich_id', on_delete=django.db.models.deletion.CASCADE, to='breadcat.sandwich'),
        ),
    ]
