# Generated by Django 3.2 on 2021-05-01 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breadcat', '0005_auto_20210501_1747'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sandwich',
        ),
    ]
