# Generated by Django 3.2 on 2021-05-01 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breadcat', '0007_sandwich'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sandwich',
        ),
    ]
